Add v3-megatron-sakura pretrain installer
llm-jp/scripts pull request #1
Opened 2024-07-24 12:12 UTC by odashi

v3 モデル用 Megatron-LM を Sakura クラスタにローカルインストールするためのスクリプトです。

2024-07-24 12:48 UTC, junjiechen-chris commented
ざっと見て問題ないと思います。手元にパソコンがないため、すぐにスクリプトの検証が難しい状態です。明日中検証をします

2024-07-24 12:50 UTC, junjiechen-chris reviewed
/home/userがハード的に指定されています。

2024-07-24 12:50 UTC, junjiechen-chris commented on installers/pretrain/v3-megatron-sakura/README.md
> +echo 'export PATH="/home/user/.pyenv/bin:$PATH"' >> ~/.bashrc
ここは/home/<各自のusername>のつもりだと思います。<user>を$(whoami)にすればいかがでしょうか

2024-07-26 09:46 UTC, YumaTsuta submitted a review, later dismissed

2024-07-26 09:54 UTC, odashi commented on installers/pretrain/v3-megatron-sakura/install.sh
> +pip install -U pip cmake wheel ninja
@YumaTsuta ありがとうございます。suggestion機能を使ってもらえるとWebからワンクリックで適用できるので考えてみてください。

2024-07-26 09:56 UTC, odashi commented on installers/pretrain/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/apex -b 24.04.01
セキュリティアップデートなどでタグが変更される可能性があるので、基本的にはタグがある場合はcommit IDより優先したいです。

2024-07-26 14:11 UTC, junjiechen-chris commented on installers/pretrain/v3-megatron-sakura/install.sh
> +git clone git@github.com:llm-jp/Megatron-LM -b nii-geniac
ここはllm-jp/Megatron-LMにaccess権限を持たなければ、以下のエラーが出ます。
```
Cloning into 'Megatron-LM'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
sshではなく、httpでcloneすればエラーがなくなります。
`git clone https://github.com/llm-jp/Megatron-LM.git -b nii-geniac`

2024-07-26 14:43 UTC, odashi commented on installers/pretrain/v3-megatron-sakura/install.sh
> +git clone git@github.com:llm-jp/Megatron-LM -b nii-geniac
そういえばそうでしたね。最近権限のあるリポジトリ以外見ないので忘れてました。修正します。

2024-07-28 23:27 UTC, odashi commented
@t0-0 @junjiechen-chris @so298 @YumaTsuta @k141303 Sakura用のインストールスクリプトです。動作確認の関係で #2 の変更も含みます。

2024-07-29 04:14 UTC, YumaTsuta commented
@odashi  検証のためにインストールスクリプトを稼働させてみたところ、TEインストール時に次のようなエラーになっていました。
ひとまずエラーの関連部分について共有します。

```
+ pushd TransformerEngine
+ MAX_JOBS=32
+ NVTE_FRAMEWORK=pytorch
+ pip install -v --no-cache-dir --no-build-isolation ./
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-toolkit/12.1'
  running egg_info
  creating /tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info
  writing /tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-l7mctz39/transformer_engine.egg-info/SOURCES.txt'
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-toolkit/12.1'
  fatal: not a git repository (or any of the parent directories): .git


  torch.__version__  = 2.3.1+cu121


  running egg_info
  creating /tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info
  writing /tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.cu' under directory 'flash_attn'
  warning: no files found matching '*.h' under directory 'flash_attn'
  warning: no files found matching '*.cuh' under directory 'flash_attn'
  warning: no files found matching '*.cpp' under directory 'flash_attn'
  warning: no files found matching '*.hpp' under directory 'flash_attn'
  adding license file 'LICENSE'
  adding license file 'AUTHORS'
  writing manifest file '/tmp/pip-pip-egg-info-h_0mjcs0/flash_attn.egg-info/SOURCES.txt'
  Running command python setup.py bdist_wheel
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-toolkit/12.1'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-310
  creating build/lib.linux-x86_64-cpython-310/transformer_engine
  copying transformer_engine/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/common
  copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common
  copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/distributed.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/profile.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/cpp_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/recompute.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/constants.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  copying transformer_engine/paddle/fp8_buffer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  copying transformer_engine/jax/fused_attn.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/jax
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/float8_tensor.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/cpu_offload.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/attention.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/pytorch
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/common/recipe
  copying transformer_engine/common/recipe/__init__.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/common/recipe
  creating build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/layernorm_mlp.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/softmax.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/transformer.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/linear.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/layernorm_linear.py -> build/lib.linux-x86_64-cpython-310/transformer_engine/paddle/layer
  copying transformer_engine/paddle/layer/base.py -> build/lib.linux-x86_6 [...]

2024-07-29 04:34 UTC, so298 commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
@odashi 
https://docs.nvidia.com/deeplearning/transformer-engine-releases/release-1.4/user-guide/installation.html#installation-from-source

`--recursive` が足りなさそうですね。 @YumaTsuta さんのエラーもそれが原因な気がします

2024-07-29 04:40 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
確かにそんなこと書いてありますね 
`Try running 'git submodule update   --init --recursive' within the Transformer Engine source.`

2024-07-29 04:42 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
あーっこれは初歩的でした…リポジトリ指定してpip installするのではなくそーすつりーほしいなと思って変更したとき、git submodule init書くのを忘れていました。

2024-07-29 06:45 UTC, YumaTsuta commented
@odashi 勘違いしてreview dismiss してしまいましたが、requirements.txtのバージョン固定お願いします。
リポジトリを取得する際にタグで取得しているので、requirementsについてもパッチバージョンはアップデート可にしても良いかと思われます

2024-07-29 08:35 UTC, odashi commented
@YumaTsuta patchにbreaking changeを含むか含まないかはライブラリごとの管理方針によるので、一律にそうと決めてよいかどうかは謎です。一番安全なのは完全に固定なので、具体的に問題が発生するまではすべて==にしようと思います。
このスクリプトではGENIACの再現はせず、Sakuraで動いたバージョンで固定します。

2024-07-29 08:45 UTC, odashi commented
`sakura:/data/experiments/1/environment/venv` にインストールされているものからバージョン番号を起こしました。

2024-07-29 13:31 UTC, YumaTsuta reviewed
Approveしても良いのですが、細かい部分で気になったのでコメントしています。

2024-07-29 13:31 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +# デフォルトでは1ノードを専有し、GPUを8枚全て使うジョブが起動します。
`cd ~/myspace` 
があると嬉しい

2024-07-29 13:31 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
（どうでも良いのですが）git clone --recursiveで良い気がする

2024-07-29 13:31 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/scripts/environment.sh
> +export PRETRAIN_TORCH_VERSION=2.3.1
(mdxやGCPと同様の)pytorch==2.2.0 揃えた方が良い気がするけれど技術的不可能でしょうか？ 
揃えられる場合、torchvision==0.17.0
（揃えられないか私の方で検証しています）

2024-07-29 13:31 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/example/train.sh
> +JOB_NAME="test-odashi"
"test-"$(whoami)の方にしておく方が良いかもです

2024-07-29 13:31 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/install.sh
> +
flash-attntionを明示的にインストールすべきか考えています。（明示的にしなかった理由があればコメントください）

2024-07-29 18:33 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/scripts/environment.sh
> +export PRETRAIN_TORCH_VERSION=2.3.1
揃えようとしたところ、稼働時に
```AttributeError: module 'transformer_engine' has no attribute 'pytorch'```
のエラーが発生したので、pytorchのバージョンを変えるだけで回避できるならこのままで良いですね

2024-07-31 07:35 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
--recurse-submodules ですかね？

2024-08-01 05:56 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
Transformer Enging の [Installation (from source)](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/installation.html#installation-from-source)で --recursiveで案内されています

```
# Clone repository, checkout stable branch, clone submodules
git clone --branch stable --recursive https://github.com/NVIDIA/TransformerEngine.git

cd TransformerEngine
export NVTE_FRAMEWORK=pytorch   # Optionally set framework
pip install .                   # Build and install
```

2024-08-01 16:57 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
`--recursive` は古いオプションで、最近のgitではhelpにも出ないと思います。両者は同じ挙動だと思うので `--recurse-submodules` にしておきます。

2024-08-01 16:59 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/example/train.sh
> +JOB_NAME="test-odashi"
fixed

2024-08-01 17:02 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/install.sh
> +
TransformerEngine v1.4のsetup.pyで2.4.2以下と指定されているので、未指定だと2.4.2がインストールされると思います。
理由は不明ですが最新のmainでも同じ条件式みたいですね。
https://github.com/NVIDIA/TransformerEngine/blob/0fbc76af3733ae997394eaf82b78ff9c0498fe91/setup.py#L288

2024-08-01 21:55 UTC, odashi commented
@YumaTsuta @junjiechen-chris @so298 @t0-0 一通り修正したので再レビューお願いします

2024-08-01 22:23 UTC, odashi commented
pyenvではなくpythonをソースビルドして含めるのを書いていましたが、それはpull requestを分けます。

2024-08-02 01:11 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/install.sh
> +git clone https://github.com/NVIDIA/TransformerEngine -b v${PRETRAIN_TRANSFORMER_ENGINE_VERSION}
なんか動かない場合がありそうなので--recursiveにします

2024-08-02 03:59 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/install.sh
> +
将来的に2.4.3以上も利用できるようなバージョン指定の修正がないかが気になりました。
実験ごとに環境を残るため大した問題にはならないので、今後問題があった時に対応する方針と考えておきます
（TransformerEngineでもバージョン管理しているので問題は起きにくそうですし）

2024-08-02 06:36 UTC, YumaTsuta requested changes
repository renameした分の修正お願いします

2024-08-02 06:36 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +git clone https://github.com/llm-jp/llm-jp-scripts
repository renameしたので、ここと次の行 llm-jp-scripts -> scriptsにお願いします

2024-08-02 10:42 UTC, odashi commented on pretrain/installers/v3-megatron-sakura/README.md
> +git clone https://github.com/llm-jp/llm-jp-scripts
@YumaTsuta 簡単な修正はsuggestion機能を使ってもらえると助かります
<img width="389" alt="無題" src="https://github.com/user-attachments/assets/010506b5-4e0e-4e3e-828b-e92351f94870">

2024-08-02 11:25 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +git clone https://github.com/llm-jp/llm-jp-scripts
すみません、その機能知りませんでした。次回から気をつけます。

2024-08-02 11:28 UTC, YumaTsuta requested changes
repository rename しました

2024-08-02 11:28 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +git clone https://github.com/llm-jp/llm-jp-scripts
```suggestion
git clone https://github.com/llm-jp/scripts
```

2024-08-02 11:28 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +cd llm-jp-scripts/pretrain/installers/v3-megatron-sakura
```suggestion
cd scripts/pretrain/installers/v3-megatron-sakura
```

2024-08-02 11:39 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +cd llm-jp-scripts/pretrain/installers/v3-megatron-sakura
```suggestion
git clone https://github.com/llm-jp/scripts
cd scripts/pretrain/installers/v3-megatron-sakura
```

2024-08-02 11:39 UTC, YumaTsuta reviewed
rename repository

2024-08-03 00:42 UTC, odashi commented
人によって動いたり動かなかったりするのにキャッシュが関係していないか調べています。

2024-08-03 10:30 UTC, YumaTsuta commented on pretrain/installers/v3-megatron-sakura/README.md
> +echo 'export PATH="/home/$(whoami)/.pyenv/bin:$PATH"' >> ~/.bashrc
```suggestion
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
```

2024-08-04 05:29 UTC, YumaTsuta approved these changes

2024-08-04 09:41 UTC, merged